language: cpp

matrix:
  include:
    - name: "GCC 4.8 (Linux)"  # GCC 4.8.5 & CMake 3.9.2
      os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.8
            - cmake
      env:
        - SET_COMPILER="export CC=gcc-4.8 && export CXX=g++-4.8"

    - name: "GCC 5.4 (Linux)"
      os: linux
      dist: xenial

    - name: "GCC 7.5 (Linux)"
      os: linux
      dist: bionic

    - name: "GCC 9.3 (Linux)"
      os: linux
      dist: focal

    - name: "Clang 3.5 (Linux)"  # Clang 3.5.0 & CMake 3.9.2
      os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-3.5
          packages:
            - clang-3.5
            - cmake
      env:
        - SET_COMPILER="export CC=clang-3.5 && export CXX=clang++-3.5"

    - name: "Clang Xcode 9.0 (OSX)"  # Clang 9.0.0 & CMake 3.9.2
      os: osx
      osx_image: xcode9

before_install:
  - eval "${SET_COMPILER}"
  - git clone https://github.com/google/googletest && cd googletest && mkdir build && cd build && git checkout 703bd9c
  - cmake -DCMAKE_CXX_FLAGS="-std=c++11" .. && make && sudo make install
  - cd ../../

install:
  - mkdir build && cd build
  - cmake -Dspoa_build_executable=ON -Dspoa_build_tests=ON -DCMAKE_BUILD_TYPE=Release .. && make

script:
  - ./bin/spoa --version
  - ./bin/spoa_test

notifications:
  email:
    on_failure: always
